depth_cloud_acc:
  ros__parameters:
    use_sim_time: false
    # subscribe topics
    input_depth_points_topic: "/internimage/segmentation/filtered/points"
    output_depth_points_topic: "/internimage/segmentation/acc_global_map"
    # accumulate fixed frame
    fixed_frame: "world"
    publish_period: 0.1  # seconds
    max_clouds: 100  # number of raw clouds retained
    enable_transform: true
    lookup_timeout: 0.5  # seconds
    log_every_n: 10
    warn_points_threshold: 1000000