octomap_update:
  ros__parameters:
    input_topic: "/internimage/segmentation/ground_points/filtered"
    # voxel cube size for clearing bbox in octomap
    log_each_bbox: true
    bbox_size: 2.4  
    target_frame: "world"
